### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by sjgknight** [massimoaria/openalexR#13] opened 2022-09-05 21:40 UTC
A recent commit has introduced a breaking change (possibly deliberate). Apologies I didn't very systematically record things as I went. I've just re-checked, this previously worked, where members$ORCID is a column of ORCID ids (without the url prepended).  I tried rolling back and the function still works at this commit `openalexR@0114bb3b3dd2c26c98b4aa8ee2da6162189a0ccf`

`oa_fetch(
  entity = "authors",
  orcid = members$ORCID
)`

Not sure if it's related but I'm having issues using oa_fetch for multiple OA identifiers (fixed by using lapply over the list of them, and using bind_rows for now), and then using the `oa2df` which gives `Error in if (!is.na(paper$biblio[1])) { : argument is of length zero` 

The `oa2bibliometrix` function either ran, but striped authors and gave odd rownames (sorry I didn't explore what field from), or `Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 865, 0
In addition: Warning messages:
1: Unknown or uninitialised column: `CR`. 
2: Unknown or uninitialised column: `concept`. `

**Comment by trangdata** [comment] 2022-09-05 23:31
Hi @sjgknight thanks for bringing this up. And thank you for your patience with the early development of this package! 🌱 Hopefully, things are getting more stable and we can push a new release to CRAN soon (in the next couple of weeks maybe? @massimoaria) 

I'm not sure which version you're using, but the following works for me in the current main branch:
``` r
library(openalexR)
oa_fetch(
  entity = "authors",
  orcid = c("0000-0003-3737-6565", "0000-0002-8517-9411")
)
#> # A tibble: 3 × 16
#>   id      displ…¹ displ…² relev…³ ids      orcid works…⁴ cited…⁵ count…⁶ affil…⁷
#>   <chr>   <chr>   <lgl>   <lgl>   <list>   <chr>   <int>   <int> <list>  <chr>  
#> 1 https:… Massim… NA      NA      <tibble> http…     102    2952 <df>    Univer…
#> 2 https:… Trang … NA      NA      <tibble> http…      80     728 <df>    Univer…
#> 3 https:… Massim… NA      NA      <tibble> http…      29      62 <df>    Univer…
#> # … with 6 more variables: affiliation_id <chr>, affiliation_ror <chr>,
#> #   affiliation_country_code <chr>, affiliation_type <chr>, x_concepts <list>,
#> #   works_api_url <chr>, and abbreviated variable names ¹​display_name,
#> #   ²​display_name_alternatives, ³​relevance_score, ⁴​works_count,
#> #   ⁵​cited_by_count, ⁶​counts_by_year, ⁷​affiliation_display_name
```

<sup>Created on 2022-09-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


> Not sure if it's related but I'm having issues using oa_fetch for multiple OA identifiers (fixed by using lapply over the list of them, and using bind_rows for now),

I recommend not doing multiple requests for a group of identifiers. Instead, I would use the different filter attributes to obtain the same final dataframe. This way, you technically only perform one query instead of multiple (hence, it's much faster, especially if you have thousands of identifiers). Could you give an example of these identifiers that you're trying to query for, please?

I'll go back and check `oa2bibliometrix`, but if you could provide a reproducible example (with [reprex](https://reprex.tidyverse.org/) for example), that would be really really helpful in helping us debug!

**Comment by sjgknight** [comment] 2022-09-06 01:42
Thanks @trangdata re: oa_fetch, it's weird, the example you give works for me. But even just dput my list of ORCIDs into a list and using that, I get: `Error in rbind(deparse.level, ...) : numbers of columns of arguments do not match`
That seems likely to be a me problem, so I'll try and look properly later in the week.

Partly because of that I'm struggling to make a useful reprex.  Again, I'll try and look properly later in the week. Insofar as it's useful, oa2biblio function gives rownames like below, and oa2df error below that. 

oa2bibliometrix(works_final_bibxd)
#>                   AU                                            RP
#> NA, , V90422530      UNIVERSITY OF ADELAIDE; ADELAIDE SA AUSTRALIA
#> NA, , V4210226857                             THE OPEN UNIVERSITY.
#>                                                                                                                                                                                                                                                      

oa2df(works_final_bibxd, "works")
#> Error in names(object) <- nm: attempt to set an attribute on NULL

**Comment by sjgknight** [comment] 2022-09-06 07:33
I'm using the current gh version (using pacman::p_load_gh_current())
I've identified an oa_fetch issue for authors, and it's just something in my data. But I have no idea what the issue is (identifier below). I have their oa_id https://api.openalex.org/people/A1912441002  

``` r
get_people <- oa_fetch(
    entity = "authors",
    orcid = "0000-0001-7482-0480")
#> Error in oa_fetch(entity = "authors", orcid = "0000-0001-7482-0480"): could not find function "oa_fetch"
```

<sup>Created on 2022-09-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

And somewhere along the way TI became display_name (either because I ran something e.g. for bibliometrix, or I know you mentioned you weren't going to rename columns so possibly that).

**Comment by trangdata** [comment] 2022-09-06 10:52
@sjgknight Thank you for pinpointing me to this particular example. 🙏🏽 💯  It is indeed a bug. 🐞  I will fix this soon! FYI next time for reprex, you want to add library(openalexR) to your clipboard also, so the error message stays the same as before.

I will double-check the rownames in oa2bibliometrix().

> And somewhere along the way TI became display_name

Yes, and I'm sorry for this change, but I think it is more robust to keep the column names as are, or prepend them with, e.g., _institution__, in cases of name collision. In [this branch](https://github.com/massimoaria/openalexR/tree/new-vignette), oa2bibliometrix() gives you both display_name and TI, primarily because I don't want to break any downstream analyses that use these columns.

**Comment by trangdata** [comment] 2022-09-10 13:12
Hi @sjgknight, thanks again for all your help investigating this! 💯 🙏🏽  The fix for your first issue has now been merged to main. Moving the second part of this to #14. 

Please reopen the issue if you still run into errors for your query.

**Closed by trangdata** 2022-09-10 13:12 UTC
